CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS unaccent;

DO $migration$
DECLARE
  unaccent_schema TEXT;
BEGIN
  SELECT namespace.nspname
  INTO STRICT unaccent_schema
  FROM pg_catalog.pg_extension installed_extension
  JOIN pg_catalog.pg_namespace namespace
    ON namespace.oid = installed_extension.extnamespace
  WHERE installed_extension.extname = 'unaccent';

  EXECUTE pg_catalog.format(
    $function$
      CREATE OR REPLACE FUNCTION public.normalize_school_name(input TEXT)
      RETURNS TEXT
      LANGUAGE sql
      IMMUTABLE
      STRICT
      SET search_path = pg_catalog
      AS $body$
        SELECT pg_catalog.regexp_replace(
          pg_catalog.lower(%I.unaccent(pg_catalog.btrim(input))),
          '\s+', ' ', 'g'
        );
      $body$;
    $function$,
    unaccent_schema
  );
END;
$migration$;

CREATE OR REPLACE FUNCTION public.normalize_uai(input TEXT)
RETURNS TEXT
LANGUAGE sql
IMMUTABLE
STRICT
SET search_path = pg_catalog
AS $$
  SELECT pg_catalog.upper(
    pg_catalog.regexp_replace(pg_catalog.btrim(input), '\s+', '', 'g')
  );
$$;

CREATE OR REPLACE FUNCTION public.auto_add_school_admin_membership()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NEW.admin_user_id IS NULL THEN
    RETURN NEW;
  END IF;

  INSERT INTO public.school_memberships (school_id, user_id, role, is_active)
  VALUES (NEW.id, NEW.admin_user_id, 'school_admin', true)
  ON CONFLICT (school_id, user_id)
  DO UPDATE SET role = 'school_admin', is_active = true;

  RETURN NEW;
END;
$$;

CREATE TABLE IF NOT EXISTS public.education_sync_runs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  scope TEXT NOT NULL CHECK (scope IN ('paris', 'france')),
  status TEXT NOT NULL DEFAULT 'running' CHECK (status IN ('running', 'completed', 'partial', 'failed')),
  source TEXT NOT NULL DEFAULT 'education_annuaire',
  checkpoint JSONB NOT NULL DEFAULT '{}'::jsonb,
  fetched_count INTEGER NOT NULL DEFAULT 0,
  inserted_count INTEGER NOT NULL DEFAULT 0,
  updated_count INTEGER NOT NULL DEFAULT 0,
  skipped_count INTEGER NOT NULL DEFAULT 0,
  error_count INTEGER NOT NULL DEFAULT 0,
  missing_count INTEGER NOT NULL DEFAULT 0,
  started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  completed_at TIMESTAMPTZ,
  duration_ms BIGINT,
  error_summary TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.education_establishments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  uai TEXT NOT NULL,
  official_name TEXT NOT NULL,
  patronym TEXT,
  denomination TEXT,
  nature_code INTEGER,
  nature_label TEXT NOT NULL,
  sector TEXT NOT NULL CHECK (sector IN ('public', 'private')),
  has_nursery BOOLEAN NOT NULL DEFAULT false,
  has_elementary BOOLEAN NOT NULL DEFAULT false,
  school_level TEXT NOT NULL CHECK (school_level IN ('nursery', 'elementary', 'primary', 'combined')),
  address_line_1 TEXT,
  address_line_2 TEXT,
  address_line_3 TEXT,
  postal_code TEXT NOT NULL,
  city TEXT NOT NULL,
  department_code TEXT NOT NULL,
  department_name TEXT,
  academy TEXT,
  academic_region TEXT,
  latitude DOUBLE PRECISION,
  longitude DOUBLE PRECISION,
  phone TEXT,
  email TEXT,
  is_active BOOLEAN NOT NULL DEFAULT true,
  source TEXT NOT NULL DEFAULT 'education_annuaire',
  source_updated_at DATE,
  synced_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_seen_run_id UUID REFERENCES public.education_sync_runs(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT education_establishments_uai_format CHECK (uai = public.normalize_uai(uai) AND uai ~ '^[0-9]{7}[A-Z]$'),
  CONSTRAINT education_establishments_uai_unique UNIQUE (uai),
  CONSTRAINT education_establishments_coordinates CHECK (
    (latitude IS NULL AND longitude IS NULL)
    OR (latitude BETWEEN -90 AND 90 AND longitude BETWEEN -180 AND 180)
  )
);

CREATE TABLE IF NOT EXISTS public.education_sync_errors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id UUID NOT NULL REFERENCES public.education_sync_runs(id) ON DELETE CASCADE,
  uai TEXT,
  message TEXT NOT NULL,
  payload JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.schools
  ADD COLUMN IF NOT EXISTS education_establishment_id UUID REFERENCES public.education_establishments(id) ON DELETE RESTRICT,
  ADD COLUMN IF NOT EXISTS education_link_status TEXT NOT NULL DEFAULT 'needs_review';

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'schools_education_link_status_check'
      AND conrelid = 'public.schools'::regclass
  ) THEN
    ALTER TABLE public.schools
      ADD CONSTRAINT schools_education_link_status_check
      CHECK (education_link_status IN ('linked', 'needs_review', 'not_applicable'));
  END IF;
END;
$$;

CREATE UNIQUE INDEX IF NOT EXISTS idx_schools_education_establishment_unique
  ON public.schools (education_establishment_id)
  WHERE education_establishment_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_education_establishments_active_scope
  ON public.education_establishments (is_active, department_code, sector, school_level);
CREATE INDEX IF NOT EXISTS idx_education_establishments_postal_code
  ON public.education_establishments (postal_code);
CREATE INDEX IF NOT EXISTS idx_education_establishments_city_trgm
  ON public.education_establishments USING gin (lower(city) gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_education_establishments_name_trgm
  ON public.education_establishments USING gin (public.normalize_school_name(official_name) gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_education_sync_runs_started
  ON public.education_sync_runs (started_at DESC);
CREATE INDEX IF NOT EXISTS idx_education_sync_errors_run
  ON public.education_sync_errors (run_id);

UPDATE public.schools s
SET education_establishment_id = e.id,
    education_link_status = 'linked',
    updated_at = now()
FROM public.education_establishments e
WHERE s.education_establishment_id IS NULL
  AND s.external_id IS NOT NULL
  AND public.normalize_uai(s.external_id) = e.uai
  AND public.normalize_uai(s.external_id) ~ '^[0-9]{7}[A-Z]$'
  AND (
    SELECT count(*) FROM public.schools candidate
    WHERE candidate.education_establishment_id IS NULL
      AND candidate.external_id IS NOT NULL
      AND public.normalize_uai(candidate.external_id) = e.uai
  ) = 1;

CREATE OR REPLACE FUNCTION public.link_legacy_school_by_exact_uai()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  UPDATE public.schools
  SET education_establishment_id = NEW.id,
      education_link_status = 'linked',
      updated_at = now()
  WHERE education_establishment_id IS NULL
    AND external_id IS NOT NULL
    AND public.normalize_uai(external_id) = NEW.uai
    AND (
      SELECT count(*) FROM public.schools candidate
      WHERE candidate.education_establishment_id IS NULL
        AND candidate.external_id IS NOT NULL
        AND public.normalize_uai(candidate.external_id) = NEW.uai
    ) = 1;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_link_legacy_school_by_exact_uai ON public.education_establishments;
CREATE TRIGGER trg_link_legacy_school_by_exact_uai
  AFTER INSERT OR UPDATE OF uai ON public.education_establishments
  FOR EACH ROW EXECUTE FUNCTION public.link_legacy_school_by_exact_uai();

CREATE OR REPLACE FUNCTION public.search_education_establishments(
  p_query TEXT,
  p_page INTEGER DEFAULT 0,
  p_page_size INTEGER DEFAULT 20
)
RETURNS TABLE (
  id UUID,
  uai TEXT,
  official_name TEXT,
  nature_label TEXT,
  sector TEXT,
  has_nursery BOOLEAN,
  has_elementary BOOLEAN,
  school_level TEXT,
  address_line_1 TEXT,
  address_line_2 TEXT,
  address_line_3 TEXT,
  postal_code TEXT,
  city TEXT,
  department_name TEXT,
  academy TEXT,
  latitude DOUBLE PRECISION,
  longitude DOUBLE PRECISION,
  is_active BOOLEAN,
  source_updated_at DATE,
  is_claimed BOOLEAN,
  rank_score INTEGER
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, extensions
AS $$
  WITH input AS (
    SELECT trim(COALESCE(p_query, '')) AS raw,
           public.normalize_school_name(COALESCE(p_query, '')) AS normalized,
           public.normalize_uai(COALESCE(p_query, '')) AS possible_uai,
           LEAST(GREATEST(COALESCE(p_page_size, 20), 1), 50) AS page_size,
           GREATEST(COALESCE(p_page, 0), 0) AS page_number
  )
  SELECT e.id, e.uai, e.official_name, e.nature_label, e.sector,
         e.has_nursery, e.has_elementary, e.school_level,
         e.address_line_1, e.address_line_2, e.address_line_3,
         e.postal_code, e.city, e.department_name, e.academy,
         e.latitude, e.longitude, e.is_active, e.source_updated_at,
         EXISTS (
           SELECT 1 FROM public.schools s
           WHERE s.education_establishment_id = e.id
             AND s.admin_user_id IS NOT NULL
         ) AS is_claimed,
         CASE
           WHEN e.uai = i.possible_uai THEN 100
           WHEN e.postal_code = i.raw THEN 95
           WHEN public.normalize_school_name(e.official_name) = i.normalized THEN 90
           WHEN public.normalize_school_name(e.official_name) LIKE i.normalized || '%' THEN 85
           WHEN public.normalize_school_name(e.city) = i.normalized THEN 80
           WHEN public.normalize_school_name(e.official_name) LIKE '%' || i.normalized || '%' THEN 75
           ELSE GREATEST(
             round(similarity(public.normalize_school_name(e.official_name), i.normalized) * 70)::integer,
             round(similarity(public.normalize_school_name(e.city), i.normalized) * 65)::integer
           )
         END AS rank_score
  FROM public.education_establishments e
  CROSS JOIN input i
  WHERE length(i.raw) >= 2
    AND (
      e.uai = i.possible_uai
      OR e.postal_code LIKE i.raw || '%'
      OR public.normalize_school_name(e.official_name) LIKE '%' || i.normalized || '%'
      OR public.normalize_school_name(e.city) LIKE '%' || i.normalized || '%'
      OR public.normalize_school_name(COALESCE(e.address_line_1, '')) LIKE '%' || i.normalized || '%'
      OR similarity(public.normalize_school_name(e.official_name), i.normalized) > 0.18
      OR similarity(public.normalize_school_name(e.city), i.normalized) > 0.25
    )
  ORDER BY rank_score DESC, e.is_active DESC, e.official_name, e.uai
  LIMIT (SELECT page_size FROM input)
  OFFSET (SELECT page_number * page_size FROM input);
$$;

CREATE OR REPLACE FUNCTION public.get_education_establishment_by_uai(p_uai TEXT)
RETURNS TABLE (
  id UUID,
  uai TEXT,
  official_name TEXT,
  nature_label TEXT,
  sector TEXT,
  has_nursery BOOLEAN,
  has_elementary BOOLEAN,
  school_level TEXT,
  address_line_1 TEXT,
  address_line_2 TEXT,
  address_line_3 TEXT,
  postal_code TEXT,
  city TEXT,
  department_name TEXT,
  academy TEXT,
  latitude DOUBLE PRECISION,
  longitude DOUBLE PRECISION,
  is_active BOOLEAN,
  source_updated_at DATE,
  is_claimed BOOLEAN
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT e.id, e.uai, e.official_name, e.nature_label, e.sector,
         e.has_nursery, e.has_elementary, e.school_level,
         e.address_line_1, e.address_line_2, e.address_line_3,
         e.postal_code, e.city, e.department_name, e.academy,
         e.latitude, e.longitude, e.is_active, e.source_updated_at,
         EXISTS (
           SELECT 1 FROM public.schools s
           WHERE s.education_establishment_id = e.id
             AND s.admin_user_id IS NOT NULL
         ) AS is_claimed
  FROM public.education_establishments e
  WHERE e.uai = public.normalize_uai(p_uai)
    AND public.normalize_uai(p_uai) ~ '^[0-9]{7}[A-Z]$'
  LIMIT 1;
$$;

CREATE OR REPLACE FUNCTION public.claim_education_establishment_as_user(p_uai TEXT, p_user_id UUID)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_user_id UUID := p_user_id;
  v_establishment public.education_establishments%ROWTYPE;
  v_school_id UUID;
  v_school_admin_user_id UUID;
  v_profile public.user_profiles%ROWTYPE;
  v_email TEXT;
BEGIN
  IF v_user_id IS NULL THEN
    RETURN jsonb_build_object('status', 'unauthorized');
  END IF;
  IF public.normalize_uai(p_uai) !~ '^[0-9]{7}[A-Z]$' THEN
    RETURN jsonb_build_object('status', 'invalid_uai');
  END IF;

  SELECT e.* INTO v_establishment
  FROM public.education_establishments e
  WHERE e.uai = public.normalize_uai(p_uai)
  FOR UPDATE;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('status', 'not_found');
  END IF;
  IF NOT v_establishment.is_active THEN
    RETURN jsonb_build_object('status', 'inactive');
  END IF;

  SELECT up.* INTO v_profile
  FROM public.user_profiles up
  WHERE up.user_id = v_user_id;

  IF NOT FOUND OR v_profile.role <> 'school_admin' THEN
    RETURN jsonb_build_object('status', 'forbidden');
  END IF;

  SELECT s.id, s.admin_user_id INTO v_school_id, v_school_admin_user_id
  FROM public.schools s
  WHERE s.education_establishment_id = v_establishment.id;

  IF v_school_admin_user_id IS NOT NULL
     AND v_school_admin_user_id <> v_user_id THEN
    RETURN jsonb_build_object('status', 'already_claimed');
  END IF;

  IF v_school_admin_user_id IS NULL THEN
    SELECT u.email INTO v_email FROM auth.users u WHERE u.id = v_user_id;

    IF v_school_id IS NOT NULL THEN
      UPDATE public.schools
      SET name = v_establishment.official_name,
          type = v_establishment.nature_label,
          email = COALESCE(v_email, 'school+' || v_user_id::text || '@securiclick.invalid'),
          phone = COALESCE(v_profile.phone, ''),
          address = COALESCE(v_establishment.address_line_1, v_establishment.city),
          city = v_establishment.city,
          postal_code = v_establishment.postal_code,
          manager_first_name = v_profile.first_name,
          manager_last_name = v_profile.last_name,
          manager_function = 'Responsable',
          admin_user_id = v_user_id,
          verified = true,
          external_id = v_establishment.uai,
          external_source = v_establishment.source,
          synced_at = v_establishment.synced_at,
          education_link_status = 'linked',
          is_active = true,
          updated_at = now()
      WHERE id = v_school_id
        AND admin_user_id IS NULL
      RETURNING id INTO v_school_id;
    ELSE
      INSERT INTO public.schools (
        name, type, email, phone, address, city, postal_code,
        manager_first_name, manager_last_name, manager_function,
        admin_user_id, verified, external_id, external_source, synced_at,
        education_establishment_id, education_link_status
      ) VALUES (
        v_establishment.official_name,
        v_establishment.nature_label,
        COALESCE(v_email, 'school+' || v_user_id::text || '@securiclick.invalid'),
        COALESCE(v_profile.phone, ''),
        COALESCE(v_establishment.address_line_1, v_establishment.city),
        v_establishment.city,
        v_establishment.postal_code,
        v_profile.first_name,
        v_profile.last_name,
        'Responsable',
        v_user_id,
        true,
        v_establishment.uai,
        v_establishment.source,
        v_establishment.synced_at,
        v_establishment.id,
        'linked'
      )
      ON CONFLICT (education_establishment_id) WHERE education_establishment_id IS NOT NULL
      DO NOTHING
      RETURNING id INTO v_school_id;
    END IF;
  END IF;

  IF v_school_id IS NULL THEN
    RETURN jsonb_build_object('status', 'already_claimed');
  END IF;

  UPDATE public.user_profiles
  SET school_id = v_school_id, updated_at = now()
  WHERE user_id = v_user_id;

  UPDATE public.school_memberships
  SET role = 'school_admin', is_active = true
  WHERE school_id = v_school_id
    AND user_id = v_user_id;

  IF NOT FOUND THEN
    INSERT INTO public.school_memberships (school_id, user_id, role, is_active)
    VALUES (v_school_id, v_user_id, 'school_admin', true);
  END IF;

  RETURN jsonb_build_object('status', 'claimed', 'school_id', v_school_id);
END;
$$;

CREATE OR REPLACE FUNCTION public.claim_education_establishment(p_uai TEXT)
RETURNS JSONB
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT public.claim_education_establishment_as_user(p_uai, auth.uid());
$$;

CREATE OR REPLACE FUNCTION public.resolve_school_for_child(p_establishment_id UUID)
RETURNS TABLE (school_id UUID)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT s.id
  FROM public.schools s
  WHERE s.education_establishment_id = p_establishment_id
    AND s.is_active = true
    AND auth.uid() IS NOT NULL
    AND EXISTS (
      SELECT 1 FROM public.user_profiles up
      WHERE up.user_id = auth.uid() AND up.role = 'parent'
    )
  LIMIT 1;
$$;

ALTER TABLE public.education_establishments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.education_sync_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.education_sync_errors ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.education_establishments FROM PUBLIC, anon, authenticated;
REVOKE ALL ON public.education_sync_runs FROM PUBLIC, anon, authenticated;
REVOKE ALL ON public.education_sync_errors FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE ON public.education_establishments TO service_role;
GRANT SELECT, INSERT, UPDATE ON public.education_sync_runs TO service_role;
GRANT SELECT, INSERT ON public.education_sync_errors TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.education_sync_errors_id_seq TO service_role;

REVOKE ALL ON FUNCTION public.search_education_establishments(TEXT, INTEGER, INTEGER) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.get_education_establishment_by_uai(TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.claim_education_establishment(TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.claim_education_establishment_as_user(TEXT, UUID) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.resolve_school_for_child(UUID) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.search_education_establishments(TEXT, INTEGER, INTEGER) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.get_education_establishment_by_uai(TEXT) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.claim_education_establishment(TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.resolve_school_for_child(UUID) TO authenticated;

CREATE OR REPLACE FUNCTION public.protect_user_profile_identity()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
AS $$
DECLARE
  v_claim_owner NAME;
BEGIN
  SELECT pg_catalog.pg_get_userbyid(routine.proowner)
  INTO v_claim_owner
  FROM pg_catalog.pg_proc routine
  WHERE routine.oid = 'public.claim_education_establishment_as_user(text,uuid)'::regprocedure;

  IF COALESCE(auth.jwt()->>'role', '') <> 'service_role' AND auth.uid() = OLD.user_id THEN
    NEW.role := OLD.role;
    NEW.user_id := OLD.user_id;
    IF CURRENT_USER <> v_claim_owner THEN
      NEW.school_id := OLD.school_id;
    END IF;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_protect_user_profile_identity ON public.user_profiles;
CREATE TRIGGER trg_protect_user_profile_identity
  BEFORE UPDATE ON public.user_profiles
  FOR EACH ROW EXECUTE FUNCTION public.protect_user_profile_identity();

DROP POLICY IF EXISTS "user_profiles_own_all" ON public.user_profiles;
DROP POLICY IF EXISTS "user_profiles_own_select" ON public.user_profiles;
DROP POLICY IF EXISTS "user_profiles_own_update" ON public.user_profiles;
CREATE POLICY "user_profiles_own_select" ON public.user_profiles
  FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "user_profiles_own_update" ON public.user_profiles
  FOR UPDATE USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE OR REPLACE FUNCTION public.protect_official_school_identity()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
AS $$
DECLARE
  v_claim_owner NAME;
BEGIN
  SELECT pg_catalog.pg_get_userbyid(routine.proowner)
  INTO v_claim_owner
  FROM pg_catalog.pg_proc routine
  WHERE routine.oid = 'public.claim_education_establishment_as_user(text,uuid)'::regprocedure;

  IF OLD.education_establishment_id IS NOT NULL
     AND COALESCE(auth.jwt()->>'role', '') <> 'service_role' THEN
    NEW.name := OLD.name;
    NEW.type := OLD.type;
    NEW.address := OLD.address;
    NEW.city := OLD.city;
    NEW.postal_code := OLD.postal_code;
    NEW.external_id := OLD.external_id;
    NEW.external_source := OLD.external_source;
    NEW.verified := OLD.verified;
    NEW.education_establishment_id := OLD.education_establishment_id;
    NEW.education_link_status := OLD.education_link_status;
    IF CURRENT_USER <> v_claim_owner THEN
      NEW.admin_user_id := OLD.admin_user_id;
    END IF;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_protect_official_school_identity ON public.schools;
CREATE TRIGGER trg_protect_official_school_identity
  BEFORE UPDATE ON public.schools
  FOR EACH ROW EXECUTE FUNCTION public.protect_official_school_identity();

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_meta JSONB := COALESCE(NEW.raw_user_meta_data, '{}'::jsonb);
  v_role TEXT := COALESCE(NULLIF(v_meta->>'role', ''), 'parent');
  v_first TEXT;
  v_last TEXT;
  v_phone TEXT;
  v_claim JSONB;
BEGIN
  IF v_role NOT IN ('parent', 'school_admin') THEN
    v_role := 'parent';
  END IF;

  v_first := COALESCE(NULLIF(v_meta->>'first_name', ''), NULLIF(v_meta->>'manager_first_name', ''), '');
  v_last := COALESCE(NULLIF(v_meta->>'last_name', ''), NULLIF(v_meta->>'manager_last_name', ''), '');
  v_phone := NULLIF(v_meta->>'phone', '');

  INSERT INTO public.user_profiles (user_id, first_name, last_name, phone, role)
  VALUES (NEW.id, v_first, v_last, v_phone, v_role)
  ON CONFLICT (user_id) DO NOTHING;

  IF v_role = 'school_admin' THEN
    IF COALESCE(v_meta->>'directory_uai', '') = '' THEN
      RAISE EXCEPTION USING ERRCODE = 'P0001', MESSAGE = 'directory_uai_required';
    END IF;
    v_claim := public.claim_education_establishment_as_user(v_meta->>'directory_uai', NEW.id);
    IF v_claim->>'status' <> 'claimed' THEN
      RAISE EXCEPTION USING ERRCODE = 'P0001', MESSAGE = 'establishment_' || COALESCE(v_claim->>'status', 'claim_failed');
    END IF;
    UPDATE public.schools
    SET manager_function = COALESCE(NULLIF(v_meta->>'manager_function', ''), manager_function),
        updated_at = now()
    WHERE id = (v_claim->>'school_id')::uuid;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
